import { useState, useMemo } from "react";
import { Bone, BookOpen, Info, ClipboardList, Scan, FlaskConical, Copy, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import OsteoCareAssessment from "@/components/bone-health/OsteoCareAssessment";
import DexaBmdTesting from "@/components/bone-health/DexaBmdTesting";
import ZoledronicProtocol from "@/components/bone-health/ZoledronicProtocol";

const tabs = [
  { id: "assessment", label: "Assessment", icon: ClipboardList },
  { id: "summary", label: "Summary", icon: Info },
  { id: "dexa", label: "DEXA scan", icon: Scan },
  { id: "zoledronic", label: "Zoledronic infusion", icon: FlaskConical },
] as const;



type TabId = (typeof tabs)[number]["id"];

/** The v3.2 spec's `sources` array. The spec lists `sources` outside
 *  `ui.result_sections`, so it is page-level reference material rather than a
 *  section of the generated report — which is why it renders here. */
const SOURCES = [
  { label: "ISCD", url: "https://iscd.org/official-positions-2023/" },
  {
    label: "BHOF",
    url: "https://www.bonehealthandosteoporosis.org/patients/diagnosis-information/bone-density-examtesting/",
  },
  {
    label: "NOGG drugs",
    url: "https://www.nogg.org.uk/full-guideline/section-6-pharmacological-treatment-options",
  },
  {
    label: "NOGG risk",
    url: "https://www.nogg.org.uk/full-guideline/summary-main-recommendations",
  },
  {
    label: "USPSTF",
    url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/osteoporosis-screening",
  },
  {
    label: "FDA CKD warning",
    url: "https://www.fda.gov/safety/medical-product-safety-information/prolia-denosumab-drug-safety-communication-fda-adds-boxed-warning-increased-risk-severe-hypocalcemia",
  },
] as const;

export default function BoneHealth() {
  const [activeTab, setActiveTab] = useState<TabId>("assessment");
  const [copied, setCopied] = useState(false);

  const boneHealthText = useMemo(() => {
    return `BONE HEALTH & OSTEOPOROSIS CLINICAL REFERENCE
=================================================

RISK CATEGORIES & TREATMENT
---------------------------

VERY HIGH RISK (any one of the following):
• Vertebral fracture within the last 2 years.
• Multiple vertebral fractures.
• Lowest valid T-score of −3.5 or below.
• Systemic glucocorticoid ≥7.5 mg/day prednisolone equivalent for ≥3 months.
• Independently confirmed very-high FRAX against a documented policy.
• Consider: Romosozumab 210mg SC monthly x 12 months
           Abaloparatide 80mcg daily x 18 months  
           Teriparatide 20mcg daily x 24 months
• MUST follow with antiresorptive to consolidate gains

HIGH RISK (any one of the following):
• Documented hip or vertebral fragility fracture.
• Lowest valid T-score of −2.5 or below.
• FRAX above the documented local treatment threshold.
• First-line: Oral bisphosphonate (Alendronate 70mg weekly)
• Alternative: Denosumab 60mg SC every 6 months

LOW RISK:
• Lifestyle measures only
• Calcium 1000-1200mg + Vitamin D 800-2000 IU daily

DRUG SUMMARY
------------

Bisphosphonates (Antiresorptive):
• Alendronate: 70mg weekly, 5-10 years
• Risedronate: 35mg weekly, 5-10 years
• Ibandronate: 150mg monthly OR 3mg IV q3months
• Zoledronic acid: 5mg IV yearly, 3-6 years

Denosumab:
• 60mg SC every 6 months
• NEVER stop without planned bisphosphonate
• 5-10 years duration

Anabolics (Bone Builders):
• Romosozumab: 210mg monthly x 12 months (max)
• Teriparatide: 20mcg daily x 24 months (lifetime max)
• Abaloparatide: 80mcg daily x 18 months (max)

DURATION REVIEW
---------------
• Oral BP: up to 10 years
• IV BP: up to 6 years
• Denosumab: 5-10 years, no holidays

SAFETY RULES
------------
• Never stop denosumab without planned antiresorptive
• Normal BMD ≠ low risk
• Osteopenia ≠ medication indication
• Single fracture ≠ treatment failure

---
Generated by NCD-6-May Bone Health Tool`;
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(boneHealthText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([boneHealthText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bone-health-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="osteoporosis-page min-h-screen pb-24">
      <div className="max-w-5xl mx-auto px-4 py-4 space-y-4">
        <header className="space-y-1">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-2">
              <Bone className="h-6 w-6 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">Bone Health & Osteoporosis</h1>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy}>
                <Copy className="h-4 w-4 mr-1" />
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-1" />
                Download
              </Button>
            </div>
          </div>
          <p className="text-sm text-muted-foreground">
            Risk assessment, clinical modifiers, and treatment framing for postmenopausal women and men ≥50 years.
          </p>
        </header>

        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as TabId)}>
          <nav className="sticky top-0 z-40 border-y border-border/60 bg-background/95 backdrop-blur -mx-4 px-4">
            <div className="overflow-x-auto overscroll-x-contain py-1.5">
              {/* Colour is not ours to set here. The shared Tabs components in
                  `ui/tabs.tsx` already carry `header-tablist` / `header-tab`, so
                  index.css gives this strip the per-tab palette (peach / amber /
                  magenta / teal), the container tint and a solid fill + white
                  active state — all with `!important`. `h-8`, `min-w-max` and
                  `bg-muted/60` used to sit here and silently lost to those rules,
                  so they are gone rather than left looking load-bearing. Size is
                  ours: `min-h-10` + `py-2` measures 45px here (this page's root
                  is 18px, so 1rem = 18px), against the old `h-7` at 31.5px. */}
              <TabsList className="justify-start gap-1 rounded-lg p-1">
                {tabs.map(({ id, label, icon: Icon }) => (
                  <TabsTrigger key={id} value={id} className="min-h-10 gap-2 px-3.5 py-2 text-sm sm:px-4">
                    <Icon className="h-4 w-4 shrink-0" aria-hidden="true" />
                    {label}
                  </TabsTrigger>
                ))}
              </TabsList>
            </div>
          </nav>

          <TabsContent value="summary" className="mt-0 pt-2 space-y-4">
            <Card className="overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-base flex items-center gap-2">
                  <Info className="h-4 w-4 text-primary" />
                  Osteoporosis Summary
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <figure className="m-0">
                  <img
                    src="/osteoporosis-summary.jpg"
                    alt="Osteoporosis summary - diagnosis, treatment and follow-up"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </figure>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="assessment" className="mt-0 pt-2 space-y-4">
            <OsteoCareAssessment />
          </TabsContent>

          <TabsContent value="dexa" className="mt-0 pt-2">
            <DexaBmdTesting />
          </TabsContent>

          <TabsContent value="zoledronic" className="mt-0 pt-3 space-y-4">
            <ZoledronicProtocol />
          </TabsContent>
        </Tabs>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <BookOpen className="h-4 w-4 text-primary" aria-hidden="true" />
              Scope and references
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              DXA prompt: BHOF/ISCD policy (men ≥70 age-based, 50–69 risk-based). Diagnosis and
              treatment are separate from screening. NOGG-informed medication options; USPSTF
              evidence for screening men remains insufficient. Severe hypocalcemia risk with
              denosumab in advanced CKD requires specialist management. Never treat a missing
              answer as “no.”
            </p>
            <div>
              <h4 className="mb-1 font-semibold text-foreground">Key references</h4>
              <ul className="space-y-1">
                {SOURCES.map((source) => (
                  <li key={source.label}>
                    •{" "}
                    <a
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary hover:underline"
                    >
                      {source.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
