import { useState, useMemo } from "react";
import { Bone, Info, ClipboardList, Scan, FlaskConical, Copy, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import OsteoCareAssessment from "@/components/bone-health/OsteoCareAssessment";
import DexaBmdTesting from "@/components/bone-health/DexaBmdTesting";
import ZoledronicProtocol from "@/components/bone-health/ZoledronicProtocol";

const tabs = [
  { id: "assessment", label: "Assessment", icon: ClipboardList },
  { id: "summary", label: "Summary", icon: Info },
  { id: "dexa", label: "DEXA scan", icon: Scan },
  { id: "zoledronic", label: "Zoledronic infusion", icon: FlaskConical },
] as const;



type TabId = (typeof tabs)[number]["id"];

export default function BoneHealth() {
  const [activeTab, setActiveTab] = useState<TabId>("assessment");
  const [copied, setCopied] = useState(false);

  const boneHealthText = useMemo(() => {
    return `BONE HEALTH & OSTEOPOROSIS CLINICAL REFERENCE
=================================================

RISK CATEGORIES & TREATMENT
---------------------------

VERY HIGH RISK:
• Vertebral fracture within the last 2 years.
• Multiple vertebral fractures.
• Lowest valid T-score of −3.5 or below.
• Systemic glucocorticoid ≥7.5 mg/day prednisolone equivalent for ≥3 months.
• Independently confirmed very-high FRAX against a documented policy.
• Consider: Romosozumab 210mg SC monthly x 12 months
           Abaloparatide 80mcg daily x 18 months  
           Teriparatide 20mcg daily x 24 months
• MUST follow with antiresorptive to consolidate gains

HIGH RISK:
• Documented hip or vertebral fragility fracture.
• Lowest valid T-score of −2.5 or below.
• FRAX above the documented local treatment threshold.
• First-line: Oral bisphosphonate (Alendronate 70mg weekly)
• Alternative: Denosumab 60mg SC every 6 months

LOW RISK:
• Lifestyle measures only
• Calcium 1000-1200mg + Vitamin D 800-2000 IU daily

DRUG SUMMARY
------------

Bisphosphonates (Antiresorptive):
• Alendronate: 70mg weekly, 5-10 years
• Risedronate: 35mg weekly, 5-10 years
• Ibandronate: 150mg monthly OR 3mg IV q3months
• Zoledronic acid: 5mg IV yearly, 3-6 years

Denosumab:
• 60mg SC every 6 months
• NEVER stop without planned bisphosphonate
• 5-10 years duration

Anabolics (Bone Builders):
• Romosozumab: 210mg monthly x 12 months (max)
• Teriparatide: 20mcg daily x 24 months (lifetime max)
• Abaloparatide: 80mcg daily x 18 months (max)

DURATION REVIEW
---------------
• Oral BP: up to 10 years
• IV BP: up to 6 years
• Denosumab: 5-10 years, no holidays

SAFETY RULES
------------
• Never stop denosumab without planned antiresorptive
• Normal BMD ≠ low risk
• Osteopenia ≠ medication indication
• Single fracture ≠ treatment failure

---
Generated by NCD-6-May Bone Health Tool`;
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(boneHealthText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([boneHealthText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bone-health-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="osteoporosis-page min-h-screen pb-24">
      <div className="max-w-5xl mx-auto px-4 py-4 space-y-4">
        <header className="space-y-1">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-2">
              <Bone className="h-6 w-6 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">Bone Health & Osteoporosis</h1>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy}>
                <Copy className="h-4 w-4 mr-1" />
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-1" />
                Download
              </Button>
            </div>
          </div>
          <p className="text-sm text-muted-foreground">
            Risk assessment, clinical modifiers, and treatment framing for postmenopausal women and men ≥50 years.
          </p>
        </header>

        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as TabId)}>
          <nav className="sticky top-0 z-40 border-y border-border/60 bg-background/95 backdrop-blur -mx-4 px-4">
            <div className="overflow-x-auto overscroll-x-contain py-1.5">
              <TabsList className="h-8 min-w-max justify-start gap-1 rounded-lg bg-muted/60 p-1">
                {tabs.map(({ id, label, icon: Icon }) => (
                  <TabsTrigger key={id} value={id} className="h-7 gap-1.5 px-2.5 text-xs sm:text-sm">
                    <Icon className="h-3.5 w-3.5" aria-hidden="true" />
                    {label}
                  </TabsTrigger>
                ))}
              </TabsList>
            </div>
          </nav>

          <TabsContent value="summary" className="mt-0 pt-2 space-y-4">
            <Card className="overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-base flex items-center gap-2">
                  <Info className="h-4 w-4 text-primary" />
                  Osteoporosis Summary
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <figure className="m-0">
                  <img
                    src="/osteoporosis-summary.jpg"
                    alt="Osteoporosis summary - diagnosis, treatment and follow-up"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </figure>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="assessment" className="mt-0 pt-2 space-y-4">
            <OsteoCareAssessment />
          </TabsContent>

          <TabsContent value="dexa" className="mt-0 pt-2">
            <DexaBmdTesting />
          </TabsContent>

          <TabsContent value="zoledronic" className="mt-0 pt-3 space-y-4">
            <ZoledronicProtocol />
          </TabsContent>
        </Tabs>
      </div>
    </main>
  );
}
