import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, X } from "lucide-react";
import { copyToClipboard, downloadTextFile } from "@/lib/clinical-utils";

type ExportContent = {
  title: string;
  sections: {
    heading: string;
    content: string | string[];
  }[];
};

type PageExportProps = {
  content: ExportContent;
  filename?: string;
};

export function PageExport({ content, filename }: PageExportProps) {
  const [copied, setCopied] = useState(false);

  const generateText = () => {
    let text = `${content.title.toUpperCase()}\n`;
    text += `${"=".repeat(content.title.length)}\n\n`;

    content.sections.forEach((section) => {
      text += `${section.heading}\n`;
      text += `${"-".repeat(section.heading.length)}\n`;

      if (Array.isArray(section.content)) {
        section.content.forEach((item) => {
          text += `• ${item}\n`;
        });
      } else {
        text += `${section.content}\n`;
      }
      text += `\n`;
    });

    text += `\n---\nGenerated by NCD-6-May`;
    return text;
  };

  const handleCopy = async () => {
    if (await copyToClipboard(generateText(), "Results copied")) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    downloadTextFile(`${filename || "clinical-notes"}-${new Date().toISOString().split("T")[0]}.txt`, generateText());
  };

  return (
    <div className="flex gap-2">
      <Button type="button" variant="outline" size="sm" onClick={handleCopy}>
        <Copy className="h-4 w-4 mr-1" />
        {copied ? "Copied!" : "Copy"}
      </Button>
      <Button type="button" variant="outline" size="sm" onClick={handleDownload}>
        <Download className="h-4 w-4 mr-1" />
        Download
      </Button>
    </div>
  );
}
