import { useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { zoledronicAcidProtocol } from "@/data/zoledronic-protocol";
import { 
  AlertTriangle, 
  CheckCircle2, 
  ChevronDown, 
  ChevronUp, 
  ClipboardCheck, 
  FlaskConical, 
  Pipette,
  Activity,
  Copy,
  Download
} from "lucide-react";

export default function ZoledronicProtocol() {
  const [expandedSection, setExpandedSection] = useState<string | null>("screening");
  const [copied, setCopied] = useState(false);

  const sections = [
    { id: "screening", title: "Pre-Infusion Screening", icon: ClipboardCheck },
    { id: "preparation", title: "Medication Preparation", icon: FlaskConical },
    { id: "administration", title: "Administration", icon: Pipette },
    { id: "postInfusion", title: "Post-Infusion Care", icon: Activity },
    { id: "adverse", title: "Adverse Reactions", icon: AlertTriangle },
  ];

  const toggleSection = (id: string) => {
    setExpandedSection(expandedSection === id ? null : id);
  };

  // Generate plain text for export
  const protocolText = useMemo(() => {
    const p = zoledronicAcidProtocol;
    let text = `ZOLEDRONIC ACID INFUSION PROTOCOL\n`;
    text += `================================\n\n`;
    text += `Medication: ${p.medication.name} (${p.medication.brand})\n`;
    text += `Dosage: ${p.medication.dosage}\n`;
    text += `Volume: ${p.medication.volume}\n`;
    text += `Infusion Time: ≥15 minutes\n`;
    text += `Min CrCl: ≥35 mL/min\n\n`;

    text += `PRE-INFUSION SCREENING\n`;
    text += `---------------------\n`;
    text += `• Renal Function: CrCl ≥ 35 mL/min (Cockcroft-Gault). Do not give if CrCl < 35.\n`;
    text += `• Serum Calcium: Normal. Correct hypocalcemia first.\n`;
    text += `• Dental: Check for ONJ risk.\n`;
    text += `• Hydration: At least 2 glasses of fluids before arrival.\n\n`;

    text += `MEDICATION PREPARATION\n`;
    text += `---------------------\n`;
    text += `• Temperature: Equilibrate to room temperature if refrigerated.\n`;
    text += `• Visual: Check for particulates, discoloration.\n`;
    text += `• Line: Dedicated vented IV line.\n`;
    text += `⚠️ CRITICAL: Never contact calcium-containing solutions (LR, etc.)\n\n`;

    text += `ADMINISTRATION\n`;
    text += `--------------\n`;
    text += `• Rate: 100 mL over ≥15 minutes.\n`;
    text += `• Flush: 10 mL Normal Saline after infusion.\n`;
    text += `• Monitor: 15-30 minutes for reactions.\n`;
    text += `• Pre-med: Acetaminophen per orders.\n\n`;

    text += `POST-INFUSION CARE\n`;
    text += `-----------------\n`;
    text += `• Observe: 15-30 minutes post-infusion.\n`;
    text += `• Hydration: Maintain oral fluids rest of day.\n`;
    text += `• Education: Flu-like symptoms may occur 24-72h.\n`;
    text += `• Report: Severe bone pain, muscle spasms, tingling mouth.\n\n`;

    text += `ADVERSE REACTIONS\n`;
    text += `-----------------\n`;
    text += `Acute: Fever, myalgia, arthralgia, flu-like symptoms.\n`;
    text += `Serious: Hypocalcemia, ONJ, atypical femoral fractures, renal dysfunction.\n\n`;

    text += `CONTRAINDICATIONS\n`;
    text += `----------------\n`;
    text += `${p.contraindications.join(", ")}\n\n`;

    text += `NURSING CHECKLIST\n`;
    text += `----------------\n`;
    p.nursingChecklist.forEach(item => {
      text += `${item}\n`;
    });

    text += `\n---\nGenerated by NCD-6-May Bone Health Tool`;
    return text;
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(protocolText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([protocolText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `zoledronic-protocol-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card className="overflow-hidden">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              <FlaskConical className="h-5 w-5 text-primary" />
              {zoledronicAcidProtocol.title}
            </CardTitle>
            <p className="text-xs text-muted-foreground mt-1">
              Version {zoledronicAcidProtocol.version} • Updated {zoledronicAcidProtocol.updated}
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              <Copy className="h-4 w-4 mr-1" />
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload}>
              <Download className="h-4 w-4 mr-1" />
              Download
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Quick Info - More Readable */}
        <div className="rounded-lg bg-blue-50 border-2 border-blue-200 p-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="text-center p-3 bg-white rounded-lg border border-blue-100">
              <div className="text-lg font-bold text-blue-700">{zoledronicAcidProtocol.medication.dosage}</div>
              <div className="text-xs text-blue-600 font-medium">DOSAGE</div>
            </div>
            <div className="text-center p-3 bg-white rounded-lg border border-blue-100">
              <div className="text-lg font-bold text-blue-700">{zoledronicAcidProtocol.medication.volume}</div>
              <div className="text-xs text-blue-600 font-medium">VOLUME</div>
            </div>
            <div className="text-center p-3 bg-white rounded-lg border border-blue-100">
              <div className="text-lg font-bold text-blue-700">≥15 min</div>
              <div className="text-xs text-blue-600 font-medium">INFUSION TIME</div>
            </div>
            <div className="text-center p-3 bg-white rounded-lg border border-blue-100">
              <div className="text-lg font-bold text-blue-700">≥35</div>
              <div className="text-xs text-blue-600 font-medium">MIN CrCl (mL/min)</div>
            </div>
          </div>
        </div>

        {/* Expandable Sections */}
        {sections.map((section) => {
          const Icon = section.icon;
          const isExpanded = expandedSection === section.id;
          
          return (
            <div key={section.id} className="rounded-lg border overflow-hidden">
              <button
                onClick={() => toggleSection(section.id)}
                className="w-full flex items-center justify-between p-3 hover:bg-muted/50 transition-colors"
              >
                <div className="flex items-center gap-2">
                  <Icon className="h-4 w-4 text-primary" />
                  <span className="font-medium text-sm">{section.title}</span>
                </div>
                {isExpanded ? (
                  <ChevronUp className="h-4 w-4 text-muted-foreground" />
                ) : (
                  <ChevronDown className="h-4 w-4 text-muted-foreground" />
                )}
              </button>
              
              {isExpanded && (
                <div className="px-3 pb-3 border-t pt-3 space-y-2">
                  {section.id === "screening" && (
                    <>
                      <div className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 shrink-0" />
                        <div>
                          <div className="font-medium text-sm">Renal Function</div>
                          <div className="text-xs text-muted-foreground">CrCl ≥ 35 mL/min. Do not give if below.</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 shrink-0" />
                        <div>
                          <div className="font-medium text-sm">Serum Calcium</div>
                          <div className="text-xs text-muted-foreground">Normal limits. Correct hypocalcemia first.</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 shrink-0" />
                        <div>
                          <div className="font-medium text-sm">Dental History</div>
                          <div className="text-xs text-muted-foreground">Confirm clearance. Evaluate ONJ risk.</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 shrink-0" />
                        <div>
                          <div className="font-medium text-sm">Hydration</div>
                          <div className="text-xs text-muted-foreground">At least 2 glasses of fluids before arrival.</div>
                        </div>
                      </div>
                    </>
                  )}
                  
                  {section.id === "preparation" && (
                    <>
                      <div className="text-sm">
                        <div className="font-medium">Temperature</div>
                        <div className="text-xs text-muted-foreground">Equilibrate to room temperature if refrigerated.</div>
                      </div>
                      <div className="text-sm">
                        <div className="font-medium">Visual Inspection</div>
                        <div className="text-xs text-muted-foreground">Check for particulates, clarity, discoloration.</div>
                      </div>
                      <div className="rounded-lg bg-red-50 border border-red-200 p-3">
                        <div className="flex items-start gap-2">
                          <AlertTriangle className="h-4 w-4 text-red-600 shrink-0 mt-0.5" />
                          <div className="text-xs text-red-800">
                            <strong>CRITICAL:</strong> Must NEVER contact calcium-containing 
                            solutions (e.g., Lactated Ringer's) or divalent cations. 
                            Use separate line.
                          </div>
                        </div>
                      </div>
                    </>
                  )}
                  
                  {section.id === "administration" && (
                    <>
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-xs font-bold shrink-0">1</div>
                        <div>
                          <div className="font-medium text-sm">Infusion Rate</div>
                          <div className="text-xs text-muted-foreground">100 mL over no less than 15 minutes.</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-xs font-bold shrink-0">2</div>
                        <div>
                          <div className="font-medium text-sm">Post-Infusion Flush</div>
                          <div className="text-xs text-muted-foreground">10 mL Normal Saline (0.9% NaCl).</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-xs font-bold shrink-0">3</div>
                        <div>
                          <div className="font-medium text-sm">Monitoring</div>
                          <div className="text-xs text-muted-foreground">Observe 15-30 minutes for hypersensitivity.</div>
                        </div>
                      </div>
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-xs font-bold shrink-0">4</div>
                        <div>
                          <div className="font-medium text-sm">Pre-Medication</div>
                          <div className="text-xs text-muted-foreground">Acetaminophen per physician orders post-infusion.</div>
                        </div>
                      </div>
                    </>
                  )}
                  
                  {section.id === "postInfusion" && (
                    <>
                      <div className="text-sm">
                        <div className="font-medium">Observation</div>
                        <div className="text-xs text-muted-foreground">15-30 minutes for immediate reactions.</div>
                      </div>
                      <div className="text-sm">
                        <div className="font-medium">Hydration</div>
                        <div className="text-xs text-muted-foreground">Maintain oral fluid intake for rest of day.</div>
                      </div>
                      <div className="text-sm">
                        <div className="font-medium">Patient Education</div>
                        <ul className="text-xs text-muted-foreground ml-4 list-disc">
                          <li>Flu-like symptoms may occur within 24-72 hours</li>
                          <li>Report severe bone pain</li>
                          <li>Report muscle spasms</li>
                          <li>Report tingling around mouth (hypocalcemia)</li>
                        </ul>
                      </div>
                    </>
                  )}
                  
                  {section.id === "adverse" && (
                    <>
                      <div className="text-sm">
                        <div className="font-medium text-amber-700">Acute Phase (Common)</div>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {zoledronicAcidProtocol.adverseReactions.acutePhase.map((r, i) => (
                            <span key={i} className="text-xs bg-amber-50 text-amber-700 px-2 py-0.5 rounded">
                              {r}
                            </span>
                          ))}
                        </div>
                      </div>
                      <div className="text-sm">
                        <div className="font-medium text-red-700">Serious (Report Immediately)</div>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {zoledronicAcidProtocol.adverseReactions.serious.map((r, i) => (
                            <span key={i} className="text-xs bg-red-50 text-red-700 px-2 py-0.5 rounded">
                              {r}
                            </span>
                          ))}
                        </div>
                      </div>
                      <div className="rounded-lg bg-red-50 border border-red-200 p-3 mt-2">
                        <div className="text-xs text-red-800">
                          <strong>Contraindications:</strong> {zoledronicAcidProtocol.contraindications.join(", ")}
                        </div>
                      </div>
                    </>
                  )}
                </div>
              )}
            </div>
          );
        })}

        {/* Nursing Checklist */}
        <div className="rounded-lg border p-3">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle2 className="h-4 w-4 text-primary" />
            <span className="font-medium text-sm">Nursing Checklist</span>
          </div>
          <div className="grid grid-cols-1 gap-y-1">
            {zoledronicAcidProtocol.nursingChecklist.map((item, i) => (
              <div key={i} className="text-xs text-muted-foreground py-0.5">
                {item}
              </div>
            ))}
          </div>
        </div>

        <p className="text-[10px] text-muted-foreground">
          For clinical use only. Always follow local protocols and consult prescribing information.
        </p>
      </CardContent>
    </Card>
  );
}
